# Generated by Django 5.2 on 2025-05-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='set_number',
            new_name='seat_number',
        ),
    ]
